// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// obj_rcpp
double obj_rcpp(arma::mat L, arma::mat Y, arma::mat X, double rho);
RcppExport SEXP _jlpcr_obj_rcpp(SEXP LSEXP, SEXP YSEXP, SEXP XSEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type L(LSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(obj_rcpp(L, Y, X, rho));
    return rcpp_result_gen;
END_RCPP
}
// jac_rcpp
arma::mat jac_rcpp(arma::mat L, arma::mat Y, arma::mat X, double rho);
RcppExport SEXP _jlpcr_jac_rcpp(SEXP LSEXP, SEXP YSEXP, SEXP XSEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type L(LSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(jac_rcpp(L, Y, X, rho));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_jlpcr_obj_rcpp", (DL_FUNC) &_jlpcr_obj_rcpp, 4},
    {"_jlpcr_jac_rcpp", (DL_FUNC) &_jlpcr_jac_rcpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_jlpcr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
