# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

obj_rcpp <- function(L, Y, X, rho) {
    .Call(`_mlpcr_obj_rcpp`, L, Y, X, rho)
}

jac_rcpp <- function(L, Y, X, rho) {
    .Call(`_mlpcr_jac_rcpp`, L, Y, X, rho)
}

